version: '3.4'

services:
  sqldata:
    volumes:
    - ./db:/var/opt/mssql/data
    image:  mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=luboy#2022
      - ACCEPT_EULA=Y
    ports:
      - 8080:43


  getaway.api:
    image: ${DOCKER_REGISTRY-}getawayapi
    build:
      context: .
      dockerfile: MicroserviceClean_practice/src/Getaway-Api/Getaway.Api/Dockerfile

  najotnur.api:
    image: ${DOCKER_REGISTRY-}najotnurapi
    build:
      context: .
      dockerfile: MicroserviceClean_practice/src/NajotNur-Service/NajotNur.Api/Dockerfile

